name: sagacity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  envied: ^0.5.4+1
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  get_it: ^8.0.2
  two_dimensional_scrollables: ^0.3.3
  cached_network_image: ^3.4.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
